# Generated by Django 3.1.7 on 2021-03-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAcademica',
            fields=[
                ('idareaacademica', models.AutoField(db_column='idAreaAcademica', primary_key=True, serialize=False)),
                ('nombreareaacademica', models.CharField(db_column='nombreAreaAcademica', max_length=100)),
            ],
            options={
                'db_table': 'area_academica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaFormacion',
            fields=[
                ('idareaformacion', models.AutoField(db_column='idAreaFormacion', primary_key=True, serialize=False)),
                ('nombreareaformacion', models.CharField(db_column='nombreAreaFormacion', max_length=100)),
            ],
            options={
                'db_table': 'area_formacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntidadAcademica',
            fields=[
                ('identidadacademica', models.AutoField(db_column='idEntidadAcademica', primary_key=True, serialize=False)),
                ('nombreentidadacademica', models.CharField(db_column='nombreEntidadAcademica', max_length=100)),
            ],
            options={
                'db_table': 'entidad_academica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('folioevaluacion', models.AutoField(db_column='folioEvaluacion', primary_key=True, serialize=False)),
                ('observaciones', models.TextField()),
                ('puntajesuficiencia', models.IntegerField(db_column='puntajeSuficiencia')),
                ('puntajefinal', models.IntegerField(db_column='puntajeFinal')),
                ('puntajeconguencia', models.IntegerField(blank=True, db_column='puntajeConguencia', null=True)),
                ('puntajeimpacto', models.IntegerField(blank=True, db_column='puntajeImpacto', null=True)),
                ('puntajepertinencia', models.IntegerField(blank=True, db_column='puntajePertinencia', null=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('numeropersonal', models.AutoField(db_column='numeroPersonal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(db_column='apellidoPaterno', max_length=50)),
                ('apellidomaterno', models.CharField(db_column='apellidoMaterno', max_length=50)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechatermino', models.DateField(db_column='fechaTermino')),
                ('idcomision', models.IntegerField(db_column='idComision')),
                ('firma', models.ImageField(null=True, upload_to='firma')),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluadorEvaluacion',
            fields=[
                ('idevaluador_pei', models.AutoField(db_column='idEvaluador_PEI', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evaluador_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaEducativa',
            fields=[
                ('idexperienciaeducativa', models.AutoField(db_column='idExperienciaEducativa', primary_key=True, serialize=False)),
                ('nombreexperinciaeducativa', models.CharField(db_column='nombreExperinciaEducativa', max_length=100)),
            ],
            options={
                'db_table': 'experiencia_educativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('numeroconsecutivo', models.AutoField(db_column='numeroConsecutivo', primary_key=True, serialize=False)),
                ('numeropersonal', models.CharField(db_column='numeroPersonal', max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(db_column='apellidoPaterno', max_length=50)),
                ('apellidomaterno', models.CharField(db_column='apellidoMaterno', max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pei',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(db_column='nombreProyecto', max_length=100)),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechatermino', models.DateField(db_column='fechaTermino')),
            ],
            options={
                'db_table': 'pei',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeiEvaluado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pei_evaluado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('idprogramaeducativo', models.AutoField(db_column='idProgramaEducativo', primary_key=True, serialize=False)),
                ('nombreprogramaeducativo', models.CharField(db_column='nombreProgramaEducativo', max_length=100)),
            ],
            options={
                'db_table': 'programa_educativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoParticipante',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proyecto_participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.AutoField(db_column='idRegion', primary_key=True, serialize=False)),
                ('nombreregion', models.CharField(db_column='nombreRegion', max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('tiporol', models.CharField(db_column='tipoRol', max_length=20)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numeropersonal', models.CharField(db_column='numeroPersonal', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(db_column='apellidoPaterno', max_length=50)),
                ('apellidomaterno', models.CharField(db_column='apellidoMaterno', max_length=50)),
                ('idprogramaeducativo', models.IntegerField(blank=True, db_column='idProgramaEducativo', null=True)),
                ('idexperienciaeducativa', models.IntegerField(blank=True, db_column='idExperienciaEducativa', null=True)),
                ('identidad', models.IntegerField(blank=True, db_column='idEntidad', null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
