# Generated by Django 3.1.1 on 2020-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellidoPaterno', models.TextField(max_length=50)),
                ('apellidoMaterno', models.TextField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
